language: go
os: linux
go:
  - 1.9.x
install:
  - go get -u gopkg.in/alecthomas/gometalinter.v2
  - gometalinter.v2 --install
script:
  - if [ "$TRAVIS_PULL_REQUEST" != "false" ] || [ $TRAVIS_BRANCH == "develop" ]; then bash .deployment/travis/lint; fi