#!/bin/bash

echo "Run Lint:"
#echo "- gometalinter.v2 --deadline=100s --skip=vendor ./..."
#gometalinter.v2 --deadline=100s --skip=vendor ./...
docker run -tiv $PWD:/go/src/github.com/Sharykhin/go-users-api -w="/go/src/github.com/Sharykhin/go-users-api" -t chapal/gometalinter ./... --exclude=/usr/local/go/src --vendor
